name: apliarte_click
description: "ApliArte Click Pro - Professional auto-clicker for macOS, Windows and Linux"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  ffi: ^2.1.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  google_fonts: ^8.0.0
  hotkey_manager: ^0.2.3
  url_launcher: ^6.3.2
  win32: ^5.15.0
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
